name: main

on:
  workflow_dispatch:

jobs:
  ncdu:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2025, windows-11-arm]

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: ncdu
        release: false
        msystem: MSYS

    - name: Run ncdu
      shell: msys2 {0}
      run: |
        ncdu -0 -o ${{ matrix.os }}-C.json /C
        ncdu -0 -o ${{ matrix.os }}-D.json /D

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: |
          ${{ matrix.os }}-C.json
          ${{ matrix.os }}-D.json
